server {
    listen 80;

    # 1. Gestione del Frontend (React)
    location / {
        proxy_pass http://client:80; # "client" è il nome del servizio nel docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
   
    # 2. Gestione del Backend (Express)
    location /api/ {
        # Riscrive "/api/call" in "/call" prima di mandarlo a Express
        rewrite ^/api/(.*)$ /$1 break; 
        
        proxy_pass http://server:3000; # "server" è il nome del servizio nel docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}